name: 'Get & Cache dependencies'
description: 'Get the dependencies ( via npm ) and cache them'
inputs:
  caching: 
    description: 'Whether to cache dependencies or not'
    required: true    #controllar
    default: 'true'
runs: 
  using: 'composite'
  steps: 
  - name: Cache dependencies
    if: inputs.caching == 'true''
    id: cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/node_modules') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true'  ||  inputs.caching != "true"   #install deps if caching is not enable
    run: npm ci
    shell: bash


#this file we configure the script that can be used multiple times in the jobs
# we can make configurable inputs