name: 'Get & Cache dependencies'
description: 'Get the dependencies ( via npm ) and cache them'
runs: 
  using: 'composite'
  steps: 
  - name: Cache dependencies
    id: cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: deps-node-modules-${{ hashFiles('**/node_modules') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true'
    run: npm ci
    shell: bash


#this file we configure the script that can be used multiple times in the jobs